# This file was generated by GoReleaser. DO NOT EDIT.
cask "brizz-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "c25b132b2faafb99340cdc1061d94ab3f27c9f0dc6f063be44d92a0f49f79cc6"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "45ff82ba251545713b179b9ebdd5988ee1f3c89767d901efa1eae04e42a98cc0"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4ec52bfc36970c0ca9077b0bcd02fc5176e89de9bdf39efa0606ddaefa75690"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2733c142c179b333d9b4bbd215b0eb3b5a9426eb58fd1c9fe0daedb2e4360880"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "brizz-cli"
  desc "CLI for Brizz: understand what users want and where your agents fall short."
  homepage "https://github.com/brizzai/brizz-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brizz"

  # No zap stanza required

end
