# This file was generated by GoReleaser. DO NOT EDIT.
cask "brizz-cli" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "32645f03f017dc99a259583c8ec7356c2606e29e257d53ad8424ecf799006426"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6abcba98245c7229e1d94377f295233815c4b731060b698335eef444cbc2c03f"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dfd81160045bd38ccdc3f712a731391b23ebd51c1a427eb766238f15428f82f3"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ab5310bafb0371838fdbd5a55ae0716e67ad16e6f21127ae9051fc19f847eb12"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "brizz-cli"
  desc "CLI for Brizz: understand what users want and where your agents fall short."
  homepage "https://github.com/brizzai/brizz-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brizz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brizz"], must_succeed: false
    end
  end

  # No zap stanza required

end
