# This file was generated by GoReleaser. DO NOT EDIT.
cask "brizz-code" do
  name "brizz-code"
  desc "TUI for managing multiple Claude Code sessions in parallel"
  homepage "https://github.com/brizzai/brizz-code"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brizz-code"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    on_intel do
      url "https://github.com/brizzai/brizz-code/releases/download/v#{version}/brizz-code_#{version}_darwin_amd64.tar.gz"
      sha256 "828df886ed8304c3479150898c6d72825c94c34e080b315ff4fef363b9a12d1f"
    end
    on_arm do
      url "https://github.com/brizzai/brizz-code/releases/download/v#{version}/brizz-code_#{version}_darwin_arm64.tar.gz"
      sha256 "6eba574330b2defacd20af9d642770a4eef92dd50816931f36b6c22dd73e3033"
    end
  end

  # No zap stanza required
end
