# This file was generated by GoReleaser. DO NOT EDIT.
cask "brizz-code" do
  name "brizz-code"
  desc "TUI for managing multiple Claude Code sessions in parallel"
  homepage "https://github.com/brizzai/brizz-code"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brizz-code"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    on_intel do
      url "https://github.com/brizzai/brizz-code/releases/download/v#{version}/brizz-code_#{version}_darwin_amd64.tar.gz"
      sha256 "53bbdd6a123ea741252d2820b2bcf60df55e9a2e39b82e27fecb71118be90940"
    end
    on_arm do
      url "https://github.com/brizzai/brizz-code/releases/download/v#{version}/brizz-code_#{version}_darwin_arm64.tar.gz"
      sha256 "ae18e105d3e4be58571fc053939e61a5db8149266f0d6217c5d3cb2e8e4c9865"
    end
  end

  # No zap stanza required
end
