# This file was generated by GoReleaser. DO NOT EDIT.
cask "brizz-cli" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "846b01e941621fc6a530f87b6286d7a9fdd013975b04b0fc212431c312c88cde"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e78fa06f0441bc52636048471d15f505a0fdc9195e5bed5708b6230b2d523f57"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab408f50c510fba7fcd5761775abd29b0477818f13adc7bc7805329b30136d87"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90be0131d4729d645c62c4692a8ae6d4ffee809c266bca07ea7e9e1b60d187e8"
      url "https://github.com/brizzai/brizz-cli/releases/download/v#{version}/brizz-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "brizz-cli"
  desc "CLI for Brizz: understand what users want and where your agents fall short."
  homepage "https://github.com/brizzai/brizz-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brizz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brizz"], must_succeed: false
    end
  end

  # No zap stanza required

end
