# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleet" do
  version "2.10.0"

  on_macos do
    on_intel do
      sha256 "58c9d787501cc45fc327d22aac618713743c16f359dd1cddb674c569433ee2c9"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf8a850a61a3eba6f8110c33ae684da0611d110b10d8b94c60c2a18ac0736325"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cbafe1fc923f02be82a8a7bd5a1f8ce402f860d35f10716873968974be7c51a"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "35961ffda8d79d02af746f39c3ec93ff285a031205a77002475de6d8c829a877"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fleet"
  desc "TUI for managing multiple Claude Code sessions in parallel"
  homepage "https://github.com/brizzai/fleet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "fleet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/fleet"]
    end
  end

  # No zap stanza required

end
