# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleet" do
  version "2.22.0"

  on_macos do
    on_intel do
      sha256 "bd56f77c7a4a22c27f20a35af070967ae4269179368cede4697d82f766245f35"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9709c249278074dfac2d0eefe2883725c5664bd5a2f0f8e5f8752d1a71a8e6e7"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f5455f116ce94e1a67cc40e237bf11bdcfb29d2a009138e071dab8477a712cc"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "01e2d62c9dba0e2b311b2bd2b5fd57f706ef754efed219934cb9826cc8bffd32"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fleet"
  desc "TUI for managing multiple Claude Code sessions in parallel"
  homepage "https://github.com/brizzai/fleet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "fleet"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/fleet"]
    end
  end

  # No zap stanza required

end
