# This file was generated by GoReleaser. DO NOT EDIT.
cask "fleet" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "fc5416b2967a3baf8dab9b6860aefdc247bf2b2c262b535d7bbc43361bf2fa1f"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d6d82f176cbc1a3b35ac0ca87fee4b2f4e6aa9ffec59c6b7b03e7e612b21df7"
      url "https://github.com/brizzai/fleet/releases/download/v#{version}/fleet_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "fleet"
  desc "TUI for managing multiple Claude Code sessions in parallel"
  homepage "https://github.com/brizzai/fleet"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "fleet"

  # No zap stanza required

end
